// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: import_of_legacy_library_into_null_safe
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4EOoqH4C4HChC_e0inrfcNQ1SZlevGsE',
    appId: '1:471151213818:web:1387de55f41fd04ca11d43',
    messagingSenderId: '471151213818',
    projectId: 'myapp-f94d4',
    authDomain: 'myapp-f94d4.firebaseapp.com',
    storageBucket: 'myapp-f94d4.appspot.com',
    measurementId: 'G-NQWRQMPB4T', 
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTnItbenNrpW4DXZgVwcNJa32WPG601Yc',
    appId: '1:471151213818:android:4e53a233472d3e2fa11d43',
    messagingSenderId: '471151213818',
    projectId: 'myapp-f94d4',
    storageBucket: 'myapp-f94d4.appspot.com', 
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz7i9QwSOiZWmv3JK3Bp8fJeZRyRfx7ak',
    appId: '1:471151213818:ios:86cfdd1a6b8df776a11d43',
    messagingSenderId: '471151213818',
    projectId: 'myapp-f94d4',
    storageBucket: 'myapp-f94d4.appspot.com',
    iosBundleId: 'com.example.gglug', 
  );
}
